In [1]:
import pandas as pd
excel = pd.ExcelFile('DataSet1.xlsx')
FixCost = pd.read_excel(excel,'Fix Cost')
MatrixCost = pd.read_excel(excel,'Matrix Cost')
Demand = pd.read_excel(excel,'DemandNode')

# Reading Files

In [2]:
excel = pd.ExcelFile('DataSet1-Production.xlsx')
Availability = pd.read_excel(excel,'Availability')
Shift = pd.read_excel(excel,'Shift', usecols ="A:O")
CostShift = pd.read_excel(excel,'Shift', usecols ="P:P")
sales = pd.read_excel(excel,'sales')
salesbehavior = pd.read_excel(excel,'sales behavior')

In [3]:
Availability.head()

Employee  S1  S2  S3  S4  S5  S6  S7  S8  S9  S10  S11  S12  S13  S14  S15  \
0         1   1   1   1   1   1   1   1   0   0    1    0    0    0    0    0   
1         2   1   1   1   1   0   1   1   0   0    0    0    0    0    0    0   
2         3   1   1   1   1   1   1   1   0   0    0    0    0    1    0    0   
3         4   0   0   1   1   1   1   1   0   0    0    1    0    0    0    0   
4         5   1   1   1   1   1   1   1   0   0    0    0    0    0    0    0   

   S16  S17  S18  
0    0    0    0  
1    1    0    0  
2    0    0    0  
3    0    0    0  
4    1    0    0

In [4]:
Shift.head()

Shift  H8  H9  H10  H11  H12  H13  H14  H15  H16  H17  H18  H19  H20  H21
0    S1   1   1    1    1    0    1    1    1    1    0    0    0    0    0
1    S2   0   1    1    1    1    0    1    1    1    1    0    0    0    0
2    S3   0   0    1    1    1    1    0    1    1    1    1    0    0    0
3    S4   0   0    0    1    1    1    1    0    1    1    1    1    0    0
4    S5   0   0    0    0    1    1    1    1    1    1    1    1    0    0

In [5]:
CostShift.head()

Shift Cost
0          40
1          40
2          40
3          40
4          40

In [6]:
sales.head()

Date   Week Day  Week  Sales
0 2018-03-04    domingo     1  44889
1 2018-03-05      lunes     1  17585
2 2018-03-06     martes     1  20017
3 2018-03-07  miércoles     1  14993
4 2018-03-08     jueves     1  15914

In [7]:
salesbehavior.head()

time   %Sales WeekDay  %Sales Weekend
0      8        0.004435        0.002141
1      9        0.050000        0.014794
2     10        0.060000        0.032081
3     11        0.115565        0.053327
4     12        0.100000        0.087815

# Data manipulations

In [8]:
#DayWeek= {i:salesbehavior['%Sales WeekDay'][i] for i in range(len(salesbehavior['%Sales WeekDay']))}
#Weekeend= {i:salesbehavior['%Sales Weekend'][i] for i in range(len(salesbehavior['%Sales Weekend']))}
Weekeend=salesbehavior['%Sales Weekend'].values.flatten()
DayWeek=salesbehavior['%Sales WeekDay'].values.flatten()


In [9]:
DayWeek

array([0.0044348, 0.05     , 0.06     , 0.1155652, 0.1      , 0.07     ,
       0.04     , 0.03     , 0.07     , 0.09     , 0.1      , 0.11     ,
       0.1      , 0.06     ])

In [10]:
#Here we apply the desagregation of demand according to the day of the week
salesHour=[]
for i in range(len(sales['Sales'])):
    if (sales['Week Day'][i]=='domingo' or sales['Week Day'][i]=='sábado'):
        salesHour.append(sales['Sales'][i]*Weekeend)
    else:
        salesHour.append(sales['Sales'][i]*DayWeek)

print(type(salesHour))
len(salesHour)

<class 'list'>


30

In [11]:
#IN THIS PART, WE CALCULATE THE DEMAND OF PERSONNEL PER HOURS
import numpy as np
import math # Library used to round up numbers

empleRequirement=[]
for i in range(len(salesHour)): #se corta tamanio de m
    empleRequirement.append([math.ceil(num/1000) for num in salesHour[i]])

empleRequirement



[[1, 1, 2, 3, 4, 4, 4, 4, 4, 6, 6, 6, 5, 2],
 [1, 1, 2, 3, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2],
 [1, 2, 2, 3, 3, 2, 1, 1, 2, 2, 3, 3, 3, 2],
 [1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1],
 [1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1],
 [1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1],
 [1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 1],
 [1, 1, 2, 2, 4, 3, 3, 3, 4, 5, 5, 5, 4, 2],
 [1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1],
 [1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1],
 [1, 2, 2, 3, 3, 2, 1, 1, 2, 3, 3, 3, 3, 2],
 [1, 2, 2, 3, 3, 2, 1, 1, 2, 2, 3, 3, 3, 2],
 [1, 2, 2, 3, 3, 2, 1, 1, 2, 2, 3, 3, 3, 2],
 [1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 2],
 [1, 1, 1, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 2],
 [1, 2, 2, 4, 4, 3, 2, 1, 3, 3, 4, 4, 4, 2],
 [1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2],
 [1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1],
 [1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1],
 [1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1],
 [1, 1, 1, 2, 3, 2, 2, 2, 3, 4, 3, 4, 3, 2],
 [1, 1, 2, 2, 4, 3, 3, 3, 3, 5, 4, 5, 4, 2],
 [1, 1, 2,

# Step 2: Building the model in CPLEX

### Initializing differents sets

In [12]:
Numshift = [i for i in range(len(Shift['Shift']))] #Num of Workshift 
Numhour = [i for i in range(len(Shift.columns[1:]))] #Num of hour in the workshift
workShiftNode = [(i,j) for i in Numshift for j in Numhour] # defining the numer of shift and the hours

#Initialization of shift matrix
s=[]
for i in Numshift:
    for j in Numhour:
        s.append(Shift.iloc[i][j+1])
                 
workShift = {workShiftNode[k]: s[k] for k in range(len(s))}

#Initialization of cost matrix
costShift=[CostShift['Shift Cost'][i] for i in Numshift]



### decraring the decision variable

In [22]:
solArray = [] 
objArra = []
for c in range(len(empleRequirement)):  

    from docplex.mp.model import Model
    mdl=Model('PersonalScheduling')
    X=mdl.integer_var_dict(Numshift,name = 'x')
    
        #Objective function
    mdl.minimize(mdl.sum(X[i]*costShift[i] for i in Numshift))

    #demand must be satisfied
    for j in Numhour:
        mdl.add_constraint(mdl.sum(X[k]*workShift[(k,j)] for k in Numshift)>=empleRequirement[c][j])

    #full time workship must be assigned  
    #for i in range(7):
    #    mdl.add_constraint(X[i]>=1)
    
    #at minimun one full tourn must be assigned
    mdl.add_constraint(mdl.sum(X[i] for i in range(7))>=1)
        
    #solve the model    
    solucion=mdl.solve(log_output=False)
    
 
    solArray.append({i: int(X[i].solution_value) for i in Numshift if X[i].solution_value > 0.9})
    objArra.append(solucion.objective_value)
    
    

In [14]:
solArray

[{3: 1, 7: 1, 9: 1, 10: 1, 11: 1, 13: 1, 14: 2, 16: 3, 17: 2},
 {2: 1, 3: 1, 7: 1, 17: 2},
 {5: 1, 6: 1, 7: 1, 8: 2, 9: 1, 17: 1},
 {5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 {5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 {5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 {5: 1, 7: 1, 8: 1, 10: 1, 14: 1, 16: 1, 17: 1},
 {3: 1, 7: 1, 8: 1, 10: 2, 14: 3, 16: 2, 17: 2},
 {2: 1, 7: 1, 10: 1, 16: 1, 17: 1},
 {5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 {2: 1, 7: 1, 8: 1, 10: 1, 15: 1, 16: 1, 17: 2},
 {5: 1, 6: 1, 7: 1, 8: 2, 9: 1, 17: 1},
 {5: 1, 6: 1, 7: 1, 8: 2, 9: 1, 17: 1},
 {3: 1, 7: 1, 9: 1, 11: 1, 13: 1, 14: 1, 16: 2, 17: 2},
 {3: 1, 7: 1, 10: 1, 11: 1, 14: 2, 16: 2, 17: 2},
 {5: 2, 6: 1, 7: 1, 8: 3, 9: 1, 17: 1},
 {2: 1, 3: 1, 7: 1, 17: 2},
 {2: 1, 7: 1, 10: 1, 16: 1, 17: 1},
 {2: 1, 7: 1, 10: 1, 16: 1, 17: 1},
 {2: 1, 7: 1, 10: 1, 16: 1, 17: 1},
 {2: 1, 7: 1, 10: 2, 14: 1, 15: 1, 16: 1, 17: 2},
 {3: 1, 7: 1, 8: 1, 10: 1, 11: 1, 14: 2, 16: 2, 17: 2},
 {3: 1, 6: 1, 7: 1, 9: 1, 17: 1},
 {5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 {2: 1, 7: 1, 10: 1

In [30]:
#Objective function values
print("Cost of planing per day: ")
print(objArra)
print("\n")

#Total cost for the planning
print('Total planing cost = ',sum(objArra))

Cost of planing per day: 
[280.0, 140.0, 180.0, 140.0, 140.0, 140.0, 160.0, 260.0, 120.0, 140.0, 180.0, 180.0, 180.0, 220.0, 220.0, 240.0, 140.0, 120.0, 120.0, 120.0, 200.0, 240.0, 140.0, 140.0, 120.0, 140.0, 180.0, 280.0, 160.0, 180.0]


Total planing cost =  5200.0


# Step 3: PL assign the work shift to employees

### Definig the sets for the variables

In [31]:
#Num of day for the horizontal planning
numDays = len(sales['Week Day']) 

In [32]:
#listing the set for the weekends
setWeekend = [i for i in range(len(sales['Week Day'])) if (sales['Week Day'][i]=='domingo' or sales['Week Day'][i]=='sábado')]
setWeekend

[0, 6, 7, 13, 14, 20, 21, 27, 28]

In [33]:
#listing the umber of employee
numEmployee = [i for i in range(len(Availability['Employee']))]
numEmployee

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [34]:
#listing the number of workshift
Numshift = [i for i in range(len(Shift['Shift']))]
Numshift

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [35]:
#defining the set for all the possible altenative in the DV (employee, workshift, day)
s = []
for k in range(numDays):
    s.append([(i,j,k) for i in numEmployee for j in solArray[k]])

availaSet = []
for i in range(len(s)):
    for j in range(len(s[i])):
        availaSet.append(s[i][j])
#print(availaSet)

In [36]:
#create matrix for employee availability
#Here we read the worker disponibility
e=[]
for i in numEmployee:
    for j in Numshift:
        e.append(Availability.iloc[i][j+1])

availability = np.asarray(e,dtype= int) #Transform the list into array type  
availability = np.reshape(availability,(len(numEmployee),len(Numshift)))
print(availability)

[[1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1 1]
 [0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1 1]
 [0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1]
 [1 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1]
 [0 0 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1]
 [0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1]
 [0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1]]


### Building the LP model for the assigning scheduling

In [37]:
from docplex.mp.model import Model
mdl2=Model('AssigPersonal')

In [38]:
#create desicion variable
Y=mdl2.binary_var_dict(availaSet,name = 'Y')

In [39]:
#Objective function
mdl2.maximize(mdl.sum(Y[i] for i in availaSet))

In [40]:
#The required numer of perssonal must be assined to the workshift in a specific day
for k in range(numDays): 
    for j in solArray[k]:
        mdl2.add_constraint(mdl2.sum(Y[(i,j,k)] for i in numEmployee)==solArray[k][j])

In [41]:
#One employee must be assigned one time to a work shift in a particular day
for k in range(numDays): 
    for i in numEmployee:
        mdl2.add_constraint(mdl2.sum(Y[(i,j,k)] for j in solArray[k])<=1)

In [42]:
#every assigned workshift must respect the employee disponibility
for k in range(numDays): 
    for i in numEmployee:
        mdl2.add_constraints(Y[(i,j,k)]<=100*availability[i][j] for j in solArray[k])

In [43]:
#the employee must work maximun half the 
for i in numEmployee:
    mdl2.add_constraint(mdl2.sum(Y[(i,j,k)] for k in setWeekend for j in solArray[k])<=5)


In [44]:
print(mdl2.export_to_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: AssigPersonal

Maximize
 obj: Y_0_3_0 + Y_0_7_0 + Y_0_9_0 + Y_0_10_0 + Y_0_11_0 + Y_0_13_0 + Y_0_14_0
      + Y_0_16_0 + Y_0_17_0 + Y_1_3_0 + Y_1_7_0 + Y_1_9_0 + Y_1_10_0 + Y_1_11_0
      + Y_1_13_0 + Y_1_14_0 + Y_1_16_0 + Y_1_17_0 + Y_2_3_0 + Y_2_7_0 + Y_2_9_0
      + Y_2_10_0 + Y_2_11_0 + Y_2_13_0 + Y_2_14_0 + Y_2_16_0 + Y_2_17_0
      + Y_3_3_0 + Y_3_7_0 + Y_3_9_0 + Y_3_10_0 + Y_3_11_0 + Y_3_13_0 + Y_3_14_0
      + Y_3_16_0 + Y_3_17_0 + Y_4_3_0 + Y_4_7_0 + Y_4_9_0 + Y_4_10_0 + Y_4_11_0
      + Y_4_13_0 + Y_4_14_0 + Y_4_16_0 + Y_4_17_0 + Y_5_3_0 + Y_5_7_0 + Y_5_9_0
      + Y_5_10_0 + Y_5_11_0 + Y_5_13_0 + Y_5_14_0 + Y_5_16_0 + Y_5_17_0
      + Y_6_3_0 + Y_6_7_0 + Y_6_9_0 + Y_6_10_0 + Y_6_11_0 + Y_6_13_0 + Y_6_14_0
      + Y_6_16_0 + Y_6_17_0 + Y_7_3_0 + Y_7_7_0 + Y_7_9_0 + Y_7_10_0 + Y_7_11_0
      + Y_7_13_0 + Y_7_14_0 + Y_7_16_0 + Y_7_17_0 + Y_8_3_0 + Y_8_7_0 + Y_8_9_0
      + Y_8_10_0 + Y_8_11_0 + Y_8_1

In [45]:
solucion2=mdl2.solve(log_output=True)

Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
CPXPARAM_Read_DataCheck                          1
Tried aggregator 1 time.
MIP Presolve eliminated 3915 rows and 2438 columns.
Reduced MIP has 443 rows, 1122 columns, and 2653 nonzeros.
Reduced MIP has 1121 binaries, 1 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.02 sec. (4.18 ticks)
Found incumbent of value 212.000000 after 0.05 sec. (10.65 ticks)
Probing time = 0.01 sec. (0.83 ticks)
Tried aggregator 1 time.
MIP Presolve eliminated 235 rows and 558 columns.
Reduced MIP has 208 rows, 564 columns, and 1650 nonzeros.
Reduced MIP has 564 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.02 sec. (1.14 ticks)
Probing time = 0.00 sec. (0.51 ticks)
Tried aggregator 1 time.
Detecting symmetries...
Reduced MIP has 208 rows, 564 columns, and 1650 nonzeros.
Reduced MIP has 564 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.01 sec. (1.14 ticks)
Probing time = 0.00 sec. (0.51 ticks)
Clique table memb

In [46]:
mdl2.get_solve_status()

<JobSolveStatus.OPTIMAL_SOLUTION: 2>

In [47]:
solucion2.display()

solution for: AssigPersonal
objective: 212
Y_1_3_0 = 1
Y_3_10_0 = 1
Y_6_9_0 = 1
Y_8_16_0 = 1
Y_9_11_0 = 1
Y_10_13_0 = 1
Y_11_16_0 = 1
Y_12_14_0 = 1
Y_13_14_0 = 1
Y_14_7_0 = 1
Y_15_17_0 = 1
Y_16_17_0 = 1
Y_18_16_0 = 1
Y_5_17_1 = 1
Y_6_2_1 = 1
Y_7_3_1 = 1
Y_10_7_1 = 1
Y_11_17_1 = 1
Y_0_6_2 = 1
Y_5_17_2 = 1
Y_6_9_2 = 1
Y_7_5_2 = 1
Y_8_8_2 = 1
Y_10_8_2 = 1
Y_14_7_2 = 1
Y_0_6_3 = 1
Y_5_5_3 = 1
Y_6_9_3 = 1
Y_11_8_3 = 1
Y_16_7_3 = 1
Y_0_6_4 = 1
Y_5_5_4 = 1
Y_6_9_4 = 1
Y_11_8_4 = 1
Y_16_7_4 = 1
Y_0_6_5 = 1
Y_5_5_5 = 1
Y_6_9_5 = 1
Y_11_8_5 = 1
Y_16_7_5 = 1
Y_1_5_6 = 1
Y_3_10_6 = 1
Y_12_16_6 = 1
Y_14_17_6 = 1
Y_16_14_6 = 1
Y_17_7_6 = 1
Y_18_8_6 = 1
Y_1_3_7 = 1
Y_3_10_7 = 1
Y_5_17_7 = 1
Y_7_14_7 = 1
Y_8_16_7 = 1
Y_10_8_7 = 1
Y_13_16_7 = 1
Y_14_17_7 = 1
Y_15_10_7 = 1
Y_16_14_7 = 1
Y_17_7_7 = 1
Y_18_14_7 = 1
Y_0_2_8 = 1
Y_3_10_8 = 1
Y_5_17_8 = 1
Y_8_16_8 = 1
Y_10_7_8 = 1
Y_0_6_9 = 1
Y_5_5_9 = 1
Y_6_9_9 = 1
Y_11_8_9 = 1
Y_16_7_9 = 1
Y_0_2_10 = 1
Y_1_15_10 = 1
Y_3_10_10 = 1
Y_5_17_10 = 1
Y_8_16_10 = 

In [48]:
finalSchedule = []
#finalSchedule.append({i: int(Y[i].solution_value) for i in availaSet if Y[i].solution_value > 0.9})
finalSchedule.append({i: int(Y[i].solution_value) for i in availaSet})

In [49]:
print(type(finalSchedule))
print(len(finalSchedule[0]))
finalSchedule[0]

<class 'list'>
3560


{(0, 3, 0): 0,
 (0, 7, 0): 0,
 (0, 9, 0): 0,
 (0, 10, 0): 0,
 (0, 11, 0): 0,
 (0, 13, 0): 0,
 (0, 14, 0): 0,
 (0, 16, 0): 0,
 (0, 17, 0): 0,
 (1, 3, 0): 1,
 (1, 7, 0): 0,
 (1, 9, 0): 0,
 (1, 10, 0): 0,
 (1, 11, 0): 0,
 (1, 13, 0): 0,
 (1, 14, 0): 0,
 (1, 16, 0): 0,
 (1, 17, 0): 0,
 (2, 3, 0): 0,
 (2, 7, 0): 0,
 (2, 9, 0): 0,
 (2, 10, 0): 0,
 (2, 11, 0): 0,
 (2, 13, 0): 0,
 (2, 14, 0): 0,
 (2, 16, 0): 0,
 (2, 17, 0): 0,
 (3, 3, 0): 0,
 (3, 7, 0): 0,
 (3, 9, 0): 0,
 (3, 10, 0): 1,
 (3, 11, 0): 0,
 (3, 13, 0): 0,
 (3, 14, 0): 0,
 (3, 16, 0): 0,
 (3, 17, 0): 0,
 (4, 3, 0): 0,
 (4, 7, 0): 0,
 (4, 9, 0): 0,
 (4, 10, 0): 0,
 (4, 11, 0): 0,
 (4, 13, 0): 0,
 (4, 14, 0): 0,
 (4, 16, 0): 0,
 (4, 17, 0): 0,
 (5, 3, 0): 0,
 (5, 7, 0): 0,
 (5, 9, 0): 0,
 (5, 10, 0): 0,
 (5, 11, 0): 0,
 (5, 13, 0): 0,
 (5, 14, 0): 0,
 (5, 16, 0): 0,
 (5, 17, 0): 0,
 (6, 3, 0): 0,
 (6, 7, 0): 0,
 (6, 9, 0): 1,
 (6, 10, 0): 0,
 (6, 11, 0): 0,
 (6, 13, 0): 0,
 (6, 14, 0): 0,
 (6, 16, 0): 0,
 (6, 17, 0): 0,
 (7, 3, 0): 0

# PART 3: Output result

In [51]:
#Generating planning per day
SM = [] # monthly scheduling
dayWork = pd.DataFrame()
for k in range(numDays):
    schedulDay = []
    for i in numEmployee:
        for j in solArray[k]:
            schedulDay.append(finalSchedule[0][(i,j,k)])

    schedulDay = np.asarray(schedulDay,dtype= int) #Transform the list into array type  
    schedulDay = np.reshape(schedulDay,(len(numEmployee),len(solArray[k]))) #reshaping the number to a matrix
    
    schedulDay = pd.DataFrame(schedulDay) #transforming to a DF
    schedulDay.columns = [i for i in solArray[k]] #changing the names of the colums
    
    SM.append(schedulDay)

#Generating report for scheduling per month

empDay = pd.DataFrame(SM[0].sum(axis=1))
empDay.columns = [str(0)] 
for i in range(1,numDays):
    empDayPlus = pd.DataFrame(SM[i].sum(axis=1))
    empDayPlus.columns = [str(i)] 
    empDay=empDay.join(empDayPlus)
    
#Printing the repord
with pd.ExcelWriter('employeeSchedule.xlsx') as writer: 
    empDay.to_excel(writer, sheet_name='Month planing') #Monthly planning
    for k in range(len(SM)):
        SM[k].to_excel(writer, sheet_name=str(k)) #day by day planning

#for i in range(numDays)
#    print(SM[i].sum(axis=1))
    

In [684]:
empDay

0  1  2  3  4  5  6  7  8  9  ...  20  21  22  23  24  25  26  27  28  29
0   0  0  1  1  1  1  0  0  1  1  ...   0   1   1   1   1   0   1   1   1   1
1   1  0  0  0  0  0  1  1  0  0  ...   1   0   0   0   0   0   0   1   0   1
2   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   1   0   0
3   1  0  0  0  0  0  1  1  1  0  ...   0   1   0   0   1   0   0   0   1   1
4   0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   0
5   0  1  1  1  1  1  0  1  1  1  ...   0   0   1   1   1   1   1   1   1   1
6   1  1  1  1  1  1  0  0  0  1  ...   1   0   1   1   0   1   1   0   0   0
7   0  1  1  0  0  0  0  1  0  0  ...   1   1   1   0   0   1   1   0   1   0
8   1  0  1  0  0  0  0  1  1  0  ...   0   1   0   0   1   0   1   1   0   1
9   1  0  0  0  0  0  0  0  0  0  ...   0   1   0   0   0   0   0   1   0   0
10  1  1  1  0  0  0  0  1  1  0  ...   1   0   1   0   1   1   1   0   1   1
11  1  1  0  1  1  1  0  0  0  1  ...   1   0   0   1   0   1   0   1   1   1
12  1  0  0  0  0  0  1  0  0  0  ...   0   1   0   0   0   0   0   1   0   1
13  1  0  0  0  0  0  0  1  0  0  ...   1   1   0   0   0   0   0   0   0   0
14  1  0  1  0  0  0  1  1  0  0  ...   1   0   0   0   0   0   1   0   0   0
15  1  0  0  0  0  0  0  1  0  0  ...   1   0   0   0   0   0   0   0   0   0
16  1  0  0  1  1  1  1  1  0  1  ...   0   1   0   1   0   0   0   0   0   0
17  0  0  0  0  0  0  1  1  0  0  ...   1   1   0   0   0   0   0   1   0   0
18  1  0  0  0  0  0  1  1  0  0  ...   0   1   0   0   0   0   0   0   0   0
19  0  0  0  0  0  0  0  0  0  0  ...   0   1   0   0   0   0   0   1   1   0

[20 rows x 30 columns]

# END